### ISSUE TITLE
Loading pizza stop animation

### ISSUE THREAD

**Issue by Ralisin** [damianoimola/DeliverEase#13]
L'animazione della pizza al login, per lunghi caricamenti quali l'accesso dopo che il rest API non viene invocato da parecchio tempo, si ferma dopo un'animazione completa sembrando che l'app si blocchi

**Comment by AlessandroFinocchi** [comment]
Problemi da risolvere:
1 Quando la connessione è lenta o il server spenta
2 Quando le credenziali sono scorrette.
