### ISSUE TITLE
refactoring shift dialogs

### ISSUE THREAD

**Issue by martinalupini** [damianoimola/DeliverEase#36]
cambiare il messaggio e modificare la grafica

**Comment by damianoimola** [comment]
Quali sono gli shifts dialogs?

1. ChangeShiftDialog che viene usato nel CalendarScreen, oppure
2. WrongConstraintsDialog che viene usato in ShiftsScreen

**Comment by martinalupini** [comment]
ho fatto un primo refactoring sui bottoni e sulla surface. sul secondo bisogna rendere i messaggi di errore comprensibili agli utenti
