### ISSUE TITLE
Constraints

### ISSUE THREAD

**Issue by AlessandroFinocchi** [damianoimola/DeliverEase#37]
I vincoli sulla selezione dei rider funzionano male. Ad esempio se tutti i rider non sono selezionati, viene permesso comunque l'invio del calendario oppure se viene settato anche un solo giorno con i giusti vincoli permette l'invio.
In sostanza non viene controllata la mancanza della selezione dei rider. Il vincolo sui turni di rider viene controllato solo se ci son rider selezionati in quel giorno.

**Comment by damianoimola** [comment]
done
