### ISSUE TITLE
Shift Preference (rider) and shift Screen (admin) date after current date

### ISSUE THREAD

**Issue by martinalupini** [damianoimola/DeliverEase#39]
se impostato il valore true nella funzione weekList crasha l'applicazione perchè la variabile selectedweek è fuori dal range degli indici di mondays list.

**Comment by martinalupini** [comment]
ho messo che la schermata non appare proprio se si cliccano date antecedenti. Lascio aperta la issue se la modalità che ho fatto io non vi piace

**Comment by damianoimola** [comment]
Come vogliamo lasciare? Posso provare a modificarla io, rendendo l'intera schermata non cliccabile

**Comment by damianoimola** [comment]
done
